export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_LANGUAGE = "SET_LANGUAGE";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";


export const SEARCH_TEXT = "SEARCH_TEXT";

//User
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_WITH_FORM = "CREATE_USER_WITH_FORM";
export const RETRIEVE_USERS= "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_WITH_FORM = "UPDATE_USER_WITH_FORM";
export const DELETE_USER = "DELETE_USER";
export const GET_UNV_CENTRAL_ADMIN = "GET_UNV_CENTRAL_ADMIN";
export const GET_USER = "GET_USER";

//Center
export const GET_LIST_CENTER = "GET_LIST_CENTER";
export const GET_CENTER = "GET_CENTER";
export const GET_LIST_CENTER_FOR_SELECT = "GET_LIST_CENTER_FOR_SELECT";
export const CREATE_CENTER = "CREATE_CENTER";
export const UPDATE_CENTER = "UPDATE_CENTER";
export const ADD_MEMBER_TO_CENTER = "ADD_MEMBER_TO_CENTER";
export const REMOVE_MEMBER_TO_CENTER = "REMOVE_MEMBER_TO_CENTER";
export const DELETE_CENTER = "DELETE_CENTER";

//Permission Role
export const GET_LIST_ROLE = "GET_LIST_ROLE";
export const GET_LIST_ROLE_FOR_SELECT = "GET_LIST_ROLE_FOR_SELECT";
export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const UPDATE_PERMISSION_STATE = "UPDATE_PERMISSION_STATE"
export const CREATE_ROLE_PERMISSION = "CREATE_ROLE_PERMISSION";
export const DELETE_ROLE_PERMISSION = "DELETE_ROLE_PERMISSION";
export const GET_ROLE_DETAIL = "GET_ROLE_DETAIL";
export const EDIT_ROLE_PERMISSION = "EDIT_ROLE_PERMISSION";

export const REFRESH_TOKEN = "REFRESH_TOKEN";